### ISSUE TITLE
Asus AURA "addressable" Header support?

### ISSUE THREAD

**Issue by bp968** [Charixfox/HD120-Controller#10]
I'm not very familiar with how github works so I apologize in advance if this isn't the correct spot for this.

I'm curious if it is possible to use these fans with the ASUS Aura software through the addressable header found on the newer boards?  I've gotten the header to work flawlessly with generic ws2812 strips so was hoping to either find some fans that would work directly with the header (IE, fans that worked with standard WS2812 commands) or alternatively, to use an arduino setup to read the signals from the data pin and translate them to something the fans *do* understand.

**Comment by Charixfox** [comment]
Not quite the right spot. This is for bugs, requests, or issues with this firmware code. A better resource would be something like http://forum.corsair.com/forums/showthread.php?t=165029

In any case, you can take at least Data and Ground from the header to the LED hub and power the hub with SATA. If the header supports at least 4.5A on the +5V, you can use that as well instead of SATA power. This particular firmware (and most Arduino systems) would not be an appropriate go-between.

Information on the LED hub pin out can be found at the above forum thread. Wire at your own risk. Doing it wrong could happily fry the motherboard.

I'm going to close this issue ticket and direct you to the forums for any further questions.
