### ISSUE TITLE
SP120 Support

### ISSUE THREAD

**Issue by MetalPhreak** [Charixfox/HD120-Controller#3]
FYI - SP120 controller uses the same timing as UCS1903 "low speed" timing. Not sure what the actual chip is. Put mine on a scope and its 500ns / 1800ns low/high. 

The SP Controller that comes with the fan kit spits out enough 3x8bit values for 24 leds, with there being 4 RBG leds per fan and 6 fan ports. 

Might give your code a spin on these and see if they'll take the faster WS2812B timing.

**Comment by MetalPhreak** [comment]
SP120 works with FastLED UCS1903 but not WS2812B / WS2812 options. Anyone using your code should be able to just swap FastLED to that instead and set the correct number of LEDs (6).

Also realised each fan is only a single "LED" (ie one address) even though there are 4 leds on the pcb. 

In theory the stock controller could control 24 fans, if there was a passthrough to another 6 fan hub.

**Comment by MetalPhreak** [comment]
#define LED_TYPE            UCS1903 //SP120
#define COLOR_ORDER         BRG //SP120 color order is reversed from HD120

**Comment by Charixfox** [comment]
Correct. The SP120 RGB Fans use the UCS1903 control chip with one control chip per fan driving four LEDs. Each control chip is addressable, so counts as one "LED" even though there are four distinct packages.

Basic testing was performed with the control chip set though I didn't test against the color order, so that is something new and useful.

It was originally surmised that this project would be extreme overkill for SP fans, given all the special handling for sides and such, and the limited display capabilities of the SP fans. So the focus was on the HD fans (And I'm curious if the HD140 fans have the same strip alignment so the remap can be used in place). Is there a large enough need/want for SP support to warrant building it in for "at compile time" support?

**Comment by MetalPhreak** [comment]
Probably not worth adding it to this project. I came across the thread on the corsair forums while googling and thought I'd share what I found if anyone is interested :)
