### ISSUE TITLE
ADD HD120 Pinout to Readme

### ISSUE THREAD

**Issue by Cyrilanthony777** [Charixfox/HD120-Controller#4]
Can you add the pinout diagram for HD120 fans in the readme 
Thanks

**Comment by Charixfox** [comment]
I'm reluctant to a degree to describe the pinout of the fan's LED lines, though I probably should include the base directions that, as long as the controller is attached to USB in the same computer, the only wire needed is a single line from the Arduino pin (usually 3) to the data pin (center of three) of the "Controller" port on the fans' hub. That refinement makes it much easier for the "Average Person" to make this work.

**Comment by Cyrilanthony777** [comment]
so the left pin is GND ,middle pin is data and right pin is +5v ?

**Comment by Charixfox** [comment]
For varying definitions of "Left" and "Right", yes. Specifically, correct if the hub is face-up and you are looking at the three-pin port on the end.

On the Controller port of the hub, the default controller gets its power from the hub. An Arduino plugged in to the USB connection gets its power from USB. In SOME cases it may be necessary to link to the Ground on the hub (If there is sufficient trouble between the USB ground plain and the hub ground plain). After some effort, I realized it is better to NOT link to 5V on the hub unless you intend to power the Arduino ONLY from the hub and not have it connected to USB at all. Otherwise the USB will -probably- still be on when the computer is off, and thus powering the Arduino, which would pass-through to the LEDs, which over-draw current-wise and trip the fuse... So everything just gets Very Sad.

**Comment by Cyrilanthony777** [comment]
I got it working!!. I used only the data pin (D3) from arduino which is connected to the USB header. The 5v and GND pins are connected to the 4-pin molex from the SMPS  (Red- +5v) (Black - GND) .
Thanks.

**Comment by Charixfox** [comment]
O.o;

I would have recommended using the SATA power connector built in to the other end of the hub. And if you already did, the 5V and Ground on the Controller port of the hub are "supply" from that, not input into the hub. Ahh well. 

Glad to hear it's working! ^.^
