### ISSUE TITLE
Serial Comms Inconsistent

### ISSUE THREAD

**Issue by OnAllTwos** [Charixfox/HD120-Controller#8]
The serial communications don't work very consistently. Sometimes the command I put through will work just fine, other times it just doesn't go through at all. Many times, I will try to set something to a certain value, and it will set itself to 0 rather than what I told it to. Putting a space a the very end of the command seems to fix it sometimes.

**Comment by Charixfox** [comment]
This is not something I've heard of encountered when valid information is passed to the system. I'd need to be able to reproduce it or otherwise infer to determine what can be done about it.

What is the information you're sending? Specifically the ASCII string that is being sent across serial.

What speed was the port opened at?

What program or method is being used to send the serial data?

What type of Arduino board is it installed on?

**Comment by OnAllTwos** [comment]
Any command such as ">1 0 7" or ">1 6 4" could trigger this. Generally, it seems like pushing any numbers to live will do this, much of the time even switching the mode to 0 regardless of the value I'm trying to modify. Pushing setting to live from the set would result in only some of the settings getting pushed through and some values getting set to 0. Loading from memory always works perfectly.
     The port was opened at 115200 baud using the Arduino 1.8.5 Serial Monitor. The board being used is Arduino 2560 Mega. I've tried different usb ports, different cables, changing the data output pin, and different connectors from the hub to the Arduino, so I'm inclined to think it may be some kind of compatibility issue with my board. 
     By the way, thank you very much for making this project! I really appreciate not having to pay Corsair an extra $60 to get even simple software control >_<.

**Comment by Charixfox** [comment]
Quite welcome. This came out before the LNP too. Though the Mega is overkill and costs nearly as much. And actually may be part of the problem, due to its serial handling. Everything that I've done has been on a Pro Micro, which has more-robust serial hardware.

However I noticed that you're mentioning > commands and "pushing to live" so I think there may be some confusion about the commands, though it may also just be a terminology issue.

"Set Live" >
"Set Stage" ^
"Move stage to live" <

Those are the three common things.

For the sake of testing, and because the spaces make me wonder, what occurs if you use periods instead of spaces? 

>1.0.7
instead of 
>1 0 7

(It should cause a mode change to occur immediately on fan 1, though notably split sides in red would still be red.)

**Comment by OnAllTwos** [comment]
Sorry for my bad terminology, I did mean to say "set to live".
Replacing spaces with periods doesn't seem to do anything, so it must be the board. I'll probably just grab a pro micro 3 pack off of Amazon anyways, as the Mega I'm using is my primary experimentation board. I'll let you know if that fixes it.
Also, I'm gonna see if I can make a GUI controller in visual basic to contribute to the project a bit. Thanks again!

**Comment by Charixfox** [comment]
No problem. 
The Pro Micro uses a chip with a built-in UART, whereas the Mega has more flash and RAM, but a separate serial chip.

There actually is already a windows app that somebody is working on. I believe he posted Git and a compiled link at the forum at http://forum.corsair.com/forums/showthread.php?t=165029    You may want to take a look at the code he has already and contribute to that.

In the meantime, I seem to have hit a USB problem on my system, so I'm trying to recover that,

**Comment by BudGriffin** [comment]
I've had problems with set to live too, think it's something to do with groups changes.  I can look into it if you like.

Oh yeah, gamebuilder you have to wait at least 3 seconds before sending commands, the pause in setup can cause what look like serial data overruns (over usb?). I always enter '?' and wait for reply before typing commands or wait 3 seconds after an upload of new code.

**Comment by BudGriffin** [comment]
Tested set stage/move to live and wasn't able to duplicate the problem. Looked at the code and wasn't able to see a problem there either. gamebuilder16 can this be closed?

**Comment by OnAllTwos** [comment]
Closed. Anyways, I developed a GUI application for this controller software. If you are interested, here are the download links: 
MEGA: https://mega.nz/#!640RHRyJ!5WquBin4Sdo7E-qwRPCSpmig0YXrohGd8m6mzj1jyBM
Google Drive: https://drive.google.com/open?id=1gr9Ob6ZyHULX2g57S9D5ZplA92W5SKxg
